version: 2
jobs:
  integration-test:
    docker:
      - image: cimg/openjdk:8.0
    working_directory: ~/microsphere-java
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      # Run tests
      - run: mvn clean package

workflows:
  version: 2
  ci:
    jobs:
      - integration-test
