name: Release To Maven Central Repository

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: '0.0.1'
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
    steps:
      - run: |
          echo "Will start a Maven Central upload with version ${{ github.event.inputs.releaseversion }}"
          sudo apt-get --assume-yes --force-yes install gnupg

      - uses: actions/checkout@v4

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven
          server-id: ossrh
          server-username: ${{ secrets.OSS_SONATYPE_USERNAME }}
          server-password: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_KEY }}

      - name: Release to Maven Central Repository
        run: mvn --batch-mode clean deploy -P release -DskipTests=true -Drevision=${{ github.event.inputs.releaseversion }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
